import cover from './assets/bg2.jpg'
import cover2 from './assets/cover2.png'
import cover3 from './assets/cover3.jpg'
import cover4 from './assets/cover4.jpg'

export const homeData = [
    {
      id: 1,
      name: "Christmas on a Budget",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "CHRISTMAS ON A BUDGET follows the wealthy Efemena family as they navigate the Christmas season amidst a financial crisis. The story highlights their struggle to maintain their lavish lifestyle while ...",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Drama",
      tags: "Drama",
      cover: cover,
      video: "../video/video1.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "A Night in 2005",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Harriet Akinola, Bimbo Akintola, Chris Akwarandu, Teniola Aladese, Uzoamaka Aniunoh, Taye Arimoro, Demi Banwo, Iretiola Doyle, Shamz Garuba, Efa Iwara",
      genres: "Drama",
      tags: "Drama, Family",
      cover: cover2,
      video: "../video/video2.mp4",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Broken Hope",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Driven by vengeance, a woman embarks on a relentless mission to avenge her father’s death, even if it means sacrificing everything including her own life to take down the powerful son of her father's killer.",
      starring: "Bimbo Ademoye, Deyemi Okanlawon, Zack Orji, Jide “Jblaze” Oyegbile, Olamide Awe, Toro Aramide, Olu Adebamiwo",
      genres: "Drama",
      tags: "Drama, Romance ",
      cover: cover3,
      video: "../video/video3.mp4",
      date: "20-FEB-2010",
    },
    {
      id: 4,
      name: "Once Upon A Honeymoon",
      rating: 4.9,
      time: "2hr : 22mins",
      desc: "Sodineye and Pearl, two newlyweds, intensely in love, begin to struggle in the early days of marriage after running into a series of unforeseen issues during their honeymoon. Can their love survive these issues and what would it take?",
      starring: "Efa Iwara, Diane Russet, Uzor Arukwe, Chy Nwakanma, Baaj",
      genres: "Romance",
      tags: "Romance, Drama",
      cover: cover4,
      video: "../video/video4.mp4",
      date: "12-Aug-2015",
    },
  ]
  export const upcome = [
    {
      id: 1,
      cover: cover,
      name: "Christmas on a Budget",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: cover3,
      name: "Broken Hope",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: cover4,
      name: "Once Upon A Honeymoon",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
  ]
  export const latest = [
    {
      id: 1,
      cover: cover,
      name: "Christmas on a Budget",
      time: "2hr : 38mins",
    },
    {
      id: 2,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: cover3,
      name: "Broken Hope",
      time: "2hr : 38mins",
    },
    {
      id: 4,
      cover: cover4,
      name: "Once Upon A Honeymoon",
      time: "2hr : 38mins",
    },
    {
      id: 5,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
  ]
  
  export const trending = [
    {
      id: 1,
      name: "Christmas on a Budget",
      rating: 4.7,
      time: "2hr : 22mins",
      desc: "CHRISTMAS ON A BUDGET follows the wealthy Efemena family as they navigate the Christmas season amidst a financial crisis. The story highlights their struggle to maintain their lavish lifestyle while ...",
      starring: "Karen Gilchrist, James Earl Jones",
      genres: "Drama",
      tags: "Drama",
      cover: cover,
      video: "../video/video1.mp4",
      date: "20-Jan-1997",
    },
    {
      id: 2,
      name: "A Night in 2005",
      rating: 4.6,
      time: "2hr : 22mins",
      desc: "The island, like its inhabitants, is wholly fictional. Kong's island home in the Pacific makes its first appearance, along with Kong himself, in the 1933 film King Kong. ",
      starring: "Harriet Akinola, Bimbo Akintola, Chris Akwarandu, Teniola Aladese, Uzoamaka Aniunoh, Taye Arimoro, Demi Banwo, Iretiola Doyle, Shamz Garuba, Efa Iwara",
      genres: "Drama",
      tags: "Drama, Family",
      cover: cover2,
      video: "../video/video2.mp4",
      date: "10-JUL-2021",
    },
    {
      id: 3,
      name: "Broken Hope",
      rating: 4.8,
      time: "2hr : 22mins",
      desc: "Driven by vengeance, a woman embarks on a relentless mission to avenge her father’s death, even if it means sacrificing everything including her own life to take down the powerful son of her father's killer.",
      starring: "Bimbo Ademoye, Deyemi Okanlawon, Zack Orji, Jide “Jblaze” Oyegbile, Olamide Awe, Toro Aramide, Olu Adebamiwo",
      genres: "Drama",
      tags: "Drama, Romance ",
      cover: cover3,
      video: "../video/video3.mp4",
      date: "20-FEB-2010",
    },
  ]
  export const recommended = [
    {
      id: 5,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
    {
      id: 3,
      cover: cover3,
      name: "Broken Hope",
      time: "2hr : 38mins",
    },
    {
      id: 1,
      cover: cover,
      name: "Christmas on a Budget",
      time: "2hr : 38mins",
    },
 {
      id: 2,
      cover: cover2,
      name: "A Night in 2005",
      time: "2hr : 38mins",
    },
 {
      id: 4,
      cover: cover4,
      name: "Once Upon A Honeymoon",
      time: "2hr : 38mins",
    },
  ]